import os
import re
import subprocess

config_file = ".config"  # Path to your .config file
cmake_file = "Src/Config/sdkconfig.cmake"  # Path to the generated kconfig.cmake file
header_file = "Src/Config/sdkconfig.h"  # Path to the generated kconfig.h file


def parse_config_file_cmake(_config_file):
    config_vars = {}
    with open(_config_file, "r") as f:
        for line in f:
            # Skip comments and empty lines
            if line.startswith("#") or line.strip() == "":
                # Handle 'is not set' lines
                if "is not set" in line:
                    key = line.split()[1][7:]  # Extract key and remove 'CONFIG_' prefix
                    config_vars[key] = "unset"
                continue
            # Parse configuration line
            key, value = line.strip().split("=", 1)
            # Remove 'CONFIG_' prefix from the key name
            key = key[7:] if key.startswith("CONFIG_") else key
            # Handle quotes in the value
            if value.startswith('"') and value.endswith('"'):
                value = value[1:-1]
                # Replace escaped quotes with regular quotes
                value = value.replace('\\"', '')
            # Add to dictionary
            config_vars[key] = value
    return config_vars


def write_cmake_file(_config_vars, _cmake_file):
    with open(_cmake_file, "w") as f:
        f.write("# Automatically generated by config_to_cmake.py\n")
        for key, value in _config_vars.items():
            if value == "unset":
                f.write(f"unset({key})\n")
            else:
                f.write(f'set({key} "{value}")\n')


def convert_config_to_cmake(_config_file, _cmake_file):
    config_vars = parse_config_file_cmake(_config_file)
    write_cmake_file(config_vars, _cmake_file)


def parse_config_file_header(_config_file):
    config_vars = []
    with open(_config_file, "r") as f:
        for line in f:
            # Handle "is not set" case
            if line.startswith("# CONFIG_") and "is not set" in line:
                key = line.split("# CONFIG_")[1].split(" is not set")[0]
                config_vars.append((key, "0"))
                continue
            # Skip comments and empty lines
            if line.startswith("#") or line.strip() == "":
                continue
            # Parse configuration line
            key, value = line.strip().split("=", 1)
            # If the value is 'y', replace it with a space
            value = value.strip()
            if value == "y":
                value = "1"
            # Remove quotes
            elif (value.startswith('"') and value.endswith('"')) or (
                value.startswith("'") and value.endswith("'")
            ):
                value = value[1:-1]
            value = re.sub(r'\\"', '"', value)
            # Remove 'CONFIG_' prefix from the key name
            key = key[7:] if key.startswith("CONFIG_") else key
            # Add to list
            config_vars.append((key, value))
    return config_vars


def write_config_header(_config_vars, _header_file):
    with open(_header_file, "w") as f:
        f.write(
            "// Automatically generated by config_to_header.py, do not change the file\n"
        )
        f.write("#pragma once\n\n")

        for key, value in _config_vars:
            f.write("#define {} {}\n".format(key, value))


def convert_config_to_header(_config_file, _header_file):
    config_vars = parse_config_file_header(_config_file)
    write_config_header(config_vars, _header_file)


def get_soc_config(config_file):
    config_mapping = {
        "CONFIG_TARGET_STM32F407=y": "Src/Common/Soc/stm32f407/DefaultConf.hpp.in",
        "CONFIG_TARGET_STM32H723=y": "Src/Common/Soc/stm32h723/DefaultConf.hpp.in",
        # 可扩展其他型号
    }

    with open(config_file, "r") as f:
        for line in f:
            line = line.strip()
            if line in config_mapping:
                return config_mapping[line]
    return None


def append_macros_to_header(config_file, header_file):
    conf_path = get_soc_config(config_file)
    # read default macros from source file
    with open(conf_path, "r") as src:  # type: ignore[assignment]
        content = src.read().strip()

    # 追加到.h文件末尾
    with open(header_file, "a") as h_file:
        h_file.write("\n")
        h_file.write("/* default Soc conf */\n")
        h_file.write(content)


# Convert .config file to kconfig.h file
convert_config_to_header(config_file, header_file)

# Convert .config file to kconfig.cmake file
convert_config_to_cmake(config_file, cmake_file)

# add default macros to header file
append_macros_to_header(config_file, header_file)

# clang-format (非强制)
try:
    result = subprocess.run(['which', 'clang-format'], 
                          capture_output=True, text=True)
    clang_format_exists = result.returncode == 0
except:
    clang_format_exists = False

if clang_format_exists and os.path.exists(header_file):
    subprocess.run([
        'clang-format',
        '-i',
        '-style=file',
        header_file
    ], capture_output=True, text=True)
elif not clang_format_exists:
    print("clang-format not install，skip format sdkconfig.h")
