enhancement:
  - head-branch: [^perf/, ^feat/, ^Feat/, ^FEAT/, ^Feature/, ^feature/, perf, feat, Feat, FEAT, Feature, feature]

workflow:
  - changed-files:
    - any-glob-to-any-file: ['.github/**']

bug:
  - head-branch: [^fix/, ^hotfix/,^bug/, ^Fix/, ^FIX/, ^Bug/, ^BUG/, fix, hotfix, bug, Fix, FIX, Bug, BUG]

documentation:
- changed-files:
  - any-glob-to-any-file: ['.docs/*', '**/*.md', 'README*']

develop:
  - head-branch: [develop]

engineer:
  - head-branch: [engineer]

sentry:
  - head-branch: [sentry]

UAV:
  - head-branch: [UAV]

hero:
  - head-branch: [hero]

infantry:
  - head-branch: [infantry]

dart:
  - head-branch: [dart]
