#!/bin/sh

# 获取正确的提交消息文件路径（解决git命令参数缺失问题）
commit_msg_file=$(git rev-parse --git-path COMMIT_EDITMSG)

# 定义合法的提交消息前缀的正则表达式
valid_prefixes="^(Feat|Fix|Docs|Style|Refactor|Test|Chore|Ci|Perf|Revert|Release):"

# 提取提交消息的前缀部分，忽略前面的任何字符
prefix=$(grep -oE "^[^:]+:" "$commit_msg_file" | sed 's/^[^a-zA-Z]*//')

if ! echo "$prefix" | grep -E "$valid_prefixes"; then
  echo "提交消息不符合规范，请以'Feat:'、'Fix:'、'Docs:'、'Style:'、'Refactor:'、'Ci:'、'Perf:'、'Revert:'、'Release:'、'Test:'或'Chore:'开头。"
  exit 1
fi

echo ""
