#!/bin/sh

# 获取最近30天内的贡献者邮箱
recipients=$(git log --since="30 days ago" --pretty="%ae" | sort | uniq)

commit_msg=$(git log -1 --pretty=%B)
subject="代码仓库更新通知"
message="新的代码提交:\n$commit_msg"

for email in $recipients; do
  echo -e "$message" | mail -s "$subject" "$email"
done
