#!/bin/bash

# 要关闭编译认证可以使用 git commit -m "..." -n
RED='\033[31m'
GREEN='\033[32m'
NC='\033[0m'

git stash -u

echo -e "${GREEN}[post commit]: running cmake...${NC}"
if ! cmake -B build -G Ninja; then
  echo -e "${RED}[post commit]: Cmake config error。commit interrupt。${NC}"
  git reset --soft HEAD~1
  git stash pop
  echo -e "${RED}[post commit]: reset to previous commit${NC}"
  exit 1
fi

echo -e "${GREEN}[post commit]: running ninja...${NC}"
if ! ninja -C build; then
  echo -e "${RED}[post commit]: Ninja config error。commit interrupt。${NC}"
  git reset --soft HEAD~1
  git stash pop
  echo -e "${RED}[post commit]: reset to previous commit${NC}"
  exit 1
fi

git stash pop

echo -e "${GREEN}[post commit]: build and commit success${NC}"

exit 0
