#!/bin/sh

# clang-format
find Src -type d -name "hal" -prune -o \
  \( -name "*.h" -o -name "*.hpp" -o -name "*.cpp" -o -name "*.c" \) \
  -not -name "sdkconfig.h" -print0 |
  xargs -0 -r clang-format --dry-run --Werror --style=file

# clang-tidy
find Src -type d -name "hal" -prune -o \
  \( -name "*.h" -o -name "*.hpp" -o -name "*.cpp" \) \
  -not -name "sdkconfig.h" -print0 |
  xargs -0 -r clang-tidy --quiet --warnings-as-errors='*' --format-style=file
