execute_process(
  COMMAND git describe --tags --abbrev=0
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_VERSION
  OUTPUT_STRIP_TRAILING_WHITESPACE)

string(REGEX REPLACE "^v|-.*$" "" PROJECT_VERSION "${GIT_VERSION}")
string(REGEX REPLACE "^v" "" GIT_VERSION "${GIT_VERSION}")
