# Automatically generated by config_to_cmake.py
set(BSP_USE_CAN "y" CACHE STRING "")
set(BSP_USE_UART "y" CACHE STRING "")
set(BSP_USE_SPI "y" CACHE STRING "")
set(BSP_USE_IIC "y" CACHE STRING "")
set(TARGET_STM32F407 "y" CACHE STRING "")
set(USE_HAL_LIB "y" CACHE STRING "")
