// Automatically generated by config_to_header.py, do not change the file
#pragma once

#define TARGET_STM32F407 1
#define BSP_USE_CAN      1
#define BSP_USE_DMA      1
#define BSP_USE_PWM      1
#define BSP_USE_UART     1
#define BSP_USE_SPI      1
#define BSP_USE_TIM      1
#define USE_ALGORITHM    1
#define USE_DWT          1
#define USE_FSM          1
#define USE_HARDFAULT    1
#define USE_STM_LOG      1
#define USE_VOFA         1

/* default Soc conf */
#ifdef BSP_USE_CAN
#define HCAN1 hcan1
#define HCAN2 hcan2
#define HCAN3 hcan3
#endif

#ifdef BSP_USE_UART
#define RC_UART huart3
#endif

#ifdef BSP_USE_PWM
#define BEEP_TIMER htim4
#define BEEP_APB_FREQ HAL_RCC_GetPCLK1Freq()
#define BEEP_TIM_CHANNEL TIM_CHANNEL_3
#endif

#ifdef BSP_USE_SPI
#define IMU_SPI hspi1
#endif